name = "Retox"
license = "MIT"
licenselink = "https://github.com/allnightgrocery/hugo-theme-blueberry-detox/blob/master/LICENSE"
description = "Retox is a fork of Detox, a beautiful theme, originally designed by Jordan Bowman (@jrdnbwmn) and ported to Hugo by Andrew R. Jenkins."
homepage = "https://www.rationalbit.com"
tags = ["blog", "minimal"]
features = ["blog", "disqus", "google analytics", "pagination", "rss", "sharing options"]
min_version = 0.14

[author]
  name = "ad7d"
  homepage = "https://www.rationalbit.com"

# If porting an existing theme
[original]
  name = "Jordan Bowman"
  homepage = "http://www.jrdnbwmn.com"
  repo = "https://github.com/allnightgrocery/hugo-theme-blueberry-detox"
